"""create users table

Revision ID: 3118157fd959
Revises: 
Create Date: 2026-09-21 18:33:09.805688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3118157fd959'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('ui_language', sa.Enum('ca', 'es', 'en', name='ui_language', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('theme_preference', sa.Enum('light', 'dark', 'system', name='theme_preference', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('target_level', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='target_level', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
