"""add texts corrections and usage counters

Revision ID: 44ee4ea3bd4a
Revises: 3118157fd959
Create Date: 2026-09-21 18:44:42.518300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ee4ea3bd4a'
down_revision: Union[str, Sequence[str], None] = '3118157fd959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ui_language_used', sa.Enum('ca', 'es', 'en', name='ui_language_used', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_texts_user_id_created_at', 'texts', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('usage_counters',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('analyses_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('generations_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('original_fragment', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('grammar', 'spelling', 'vocabulary', 'punctuation', 'style', name='category', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('rule_tag', sa.Enum('verb_tense', 'subject_verb_agreement', 'articles', 'prepositions', 'word_order', 'plural_nouns', 'pronouns', 'modal_verbs', 'conditionals', 'passive_voice', 'phrasal_verbs', 'collocations', 'false_friends', 'spelling_common', 'punctuation_commas', 'capitalization', 'register_formal', 'run_on_sentence', 'other', name='rule_tag', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name='valid_range'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_rule_tag'), 'corrections', ['rule_tag'], unique=False)
    op.create_index(op.f('ix_corrections_text_id'), 'corrections', ['text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_text_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_rule_tag'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_table('usage_counters')
    op.drop_index('ix_texts_user_id_created_at', table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###
