"""add exercises and exercise attempts

Revision ID: 0f194dee9800
Revises: 44ee4ea3bd4a
Create Date: 2026-09-22 08:40:28.052479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f194dee9800'
down_revision: Union[str, Sequence[str], None] = '44ee4ea3bd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_text_id', sa.Uuid(), nullable=True),
    sa.Column('rule_tag', sa.Enum('verb_tense', 'subject_verb_agreement', 'articles', 'prepositions', 'word_order', 'plural_nouns', 'pronouns', 'modal_verbs', 'conditionals', 'passive_voice', 'phrasal_verbs', 'collocations', 'false_friends', 'spelling_common', 'punctuation_commas', 'capitalization', 'register_formal', 'run_on_sentence', 'other', name='exercise_rule_tag', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('type', sa.Enum('multiple_choice', 'fill_blank', name='exercise_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', name='exercise_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'multiple_choice' AND options IS NOT NULL) OR (type = 'fill_blank' AND options IS NULL)", name='options_match_type'),
    sa.ForeignKeyConstraint(['source_text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_user_id_status', 'exercises', ['user_id', 'status'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_attempts')
    op.drop_index('ix_exercises_user_id_status', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
